msdf-atlas-gen.exe ^
	-font "static/Outfit-Regular.ttf" ^
	-charset "charset.txt" ^
	-type mtsdf ^
	-size 64 ^
	-pxrange 2 ^
	-yorigin top ^
	-potr ^
	-pxalign on ^
	-format png ^
	-imageout outfit_atlas.png ^
	-json outfit_atlas.json
